/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.prince.gradle;

public class App {
    public String getGreeting() {
        return "Hello World!\n";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        Product product = new Product("Car", "TataMotors", 830000);

        System.out.println(product);
    }
}
